package GUI_frames;

import dfs_client.Client;
import entities.publicFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Aryan Mehta
 */
public class fileInfo extends javax.swing.JPanel {

    private publicFile file;
    private Client cl;
    
    private String fileName;
    
    public fileInfo(publicFile file,Client cl) {
        initComponents();
        this.file = file;
        this.cl = cl;
        init();
    }

    private void init(){
        fileName = file.getFileName();
        lbl_fileName.setText(fileName);
        lbl_fileCr.setText("Creator:"+file.getFile_Cr());
        lbl_last_update.setText(file.getLastUpdate());
        
        if(file.getFile_Cr().equals(cl.getClientUsername())){
            btn_delete.setEnabled(true);
        }else{
            btn_delete.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_fileCr = new javax.swing.JLabel();
        lbl_fileName = new javax.swing.JLabel();
        btn_read = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        lbl_last_update = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_fileCr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_fileCr.setText("Creator:");

        lbl_fileName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btn_read.setBackground(new java.awt.Color(204, 204, 0));
        btn_read.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_read.setForeground(new java.awt.Color(255, 255, 255));
        btn_read.setText("R");
        btn_read.setFocusPainted(false);
        btn_read.setOpaque(true);
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(51, 0, 255));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("U");
        btn_update.setFocusPainted(false);
        btn_update.setOpaque(true);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 0));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("D");
        btn_delete.setFocusPainted(false);
        btn_delete.setOpaque(true);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        lbl_last_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_read, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fileCr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_last_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fileCr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_last_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fileName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_read)
                        .addComponent(btn_update)
                        .addComponent(btn_delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readActionPerformed
        int status = cl.sendReadRequest(fileName);
        
        if(status==0){
            JOptionPane.showMessageDialog(null, "The File is being Edited!");
        }else{
            new frame_readFile(file, cl).setVisible(true);
            cl.setThread_sts(false);
        }
    }//GEN-LAST:event_btn_readActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int status = cl.sendWriteRequest(fileName);
        
        if(status==1){
            new frame_writeFile(file, cl).setVisible(true);
            cl.setThread_sts(false);
        }else{
            JOptionPane.showMessageDialog(null, "File is Already In Use!");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        cl.setThread_sts(false);
        int response = JOptionPane.showConfirmDialog(null, "Do you want to delete this File?");
        
        if(response==JOptionPane.OK_OPTION){
            int status = cl.sendDeleteRequest(fileName);
            if(status==1){
                JOptionPane.showMessageDialog(null, "File Deleted Successfully!");
                cl.sendRefreshRequest();
                cl.setThread_sts(true);
            }else if(status==2){
                JOptionPane.showMessageDialog(null, "File is in Use!");
                cl.setThread_sts(true);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel lbl_fileCr;
    private javax.swing.JLabel lbl_fileName;
    private javax.swing.JLabel lbl_last_update;
    // End of variables declaration//GEN-END:variables
}
